In [353]:
import numpy as np
import copy

digits = [1,2,3,4,5,6,7,8,9]
dict = {}   


In [354]:
#Converting Given input sudoko series inro numpy array for further processing
def preprocessing(lst):
    print('Input string : ', lst)
    
    #list with 9 elements each type = string
    l =[]
    for i in (0, 9, 18, 27, 36,45,54,63, 72):
        l.append(lst[i: i+9])
    #print(l)
    
    
    #Created list with all chars as integer
    final = []
    for line in l:
        temp = []
        for val in line:
            temp.append(int(val))
        final.append(temp)
    
    #print('Final list is : \n', final)
    
    
    arr =  np.array(final)
    return arr

lst = '004006079000000602056092300078061030509000406020540890007410920105000000840600100'   
#lst = '060900400070300006409050103090731000350209018000685020207090601600008040001002030'
output_arr =  preprocessing(lst)
print('Output array : \n',output_arr)

Input string :  004006079000000602056092300078061030509000406020540890007410920105000000840600100
Output array : 
 [[0 0 4 0 0 6 0 7 9]
 [0 0 0 0 0 0 6 0 2]
 [0 5 6 0 9 2 3 0 0]
 [0 7 8 0 6 1 0 3 0]
 [5 0 9 0 0 0 4 0 6]
 [0 2 0 5 4 0 8 9 0]
 [0 0 7 4 1 0 9 2 0]
 [1 0 5 0 0 0 0 0 0]
 [8 4 0 6 0 0 1 0 0]]


In [357]:

def block_creation(i, j, arr):
    block = []
    #block 0,1,2
    if  0<=j & j<3 and  0<=i & i<3:
        for i in range(3):
            for j in range(3):
                block.append(arr[i][j])
    
    
    if  3<=j & j<6 and  0<=i & i<3:
        for i in range(3):
            for j in range(3, 6):
                block.append(arr[i][j])
                
                
    if  6<=j & j<9 and  0<=i & i<3:
        for i in range(3):
            for j in range(6, 9):
                block.append(arr[i][j])
                
    
    #block 3,4,5
    if  0<=j & j<3 and  3<=i & i<6:
        for i in range(3, 6):
            for j in range(3):
                block.append(arr[i][j])
    
    
    if  3<=j & j<6 and  3<=i & i<6:
        for i in range(3,6):
            for j in range(3, 6):
                block.append(arr[i][j])
                
                
    if  6<=j & j<9 and  3<=i & i<6:
        for i in range(3,6): 
            for j in range(6, 9):
                block.append(arr[i][j])
                
    #block 6,7,8
    if  0<=j & j<3 and  6<=i & i<9:
        for i in range(6,9):
            for j in range(3):
                block.append(arr[i][j])
    
    
    if  3<=j & j<6 and  6<=i & i<9:
        for i in range(6, 9):
            for j in range(3, 6):
                block.append(arr[i][j])
                
                
    if  6<=j & j<9 and  6<=i & i<9:
        for i in range(6,9):
            for j in range(6, 9):
                block.append(arr[i][j])
    
    return block

print(block_creation(0,2, arr))

[0, 6, 0, 0, 7, 0, 4, 0, 9]


In [356]:
#Creating list of elements not avaliable for given block 

def block_values(i, j, arr):
    
    temp = list(filter(lambda x: x!= 0, block_creation(i,j, arr)))
    temp = list(filter(lambda x: x not in temp, digits))
    return temp
    
block_values(0, 3, arr) 


[1, 2, 4, 6, 7, 8]

In [335]:
array

array([[1, 6, 3, 9, 2, 7, 4, 8, 5],
       [5, 7, 8, 3, 1, 4, 2, 9, 6],
       [4, 2, 9, 8, 5, 6, 1, 7, 3],
       [8, 9, 2, 7, 3, 1, 5, 6, 4],
       [3, 5, 6, 2, 4, 9, 7, 1, 8],
       [7, 1, 4, 6, 8, 5, 3, 2, 9],
       [2, 8, 7, 4, 9, 3, 6, 5, 1],
       [6, 3, 5, 1, 7, 8, 9, 4, 2],
       [9, 4, 1, 5, 6, 2, 8, 3, 7]])

In [336]:
#Creating list of elements not avaliable for given row 
def row_values(i, arr):
    temp = list(filter(lambda x: x!= 0, list(arr[i])))
    
    temp1 = list(filter(lambda x: x not in temp, digits))
    
    return temp1
print(row_values(1, array))

[]


In [337]:
def zeros(arr):
    count = 0
    for i in arr:
        for j in i:
            if j==0:
                count +=1
    return count

In [338]:
#Creating list of elements not avaliable for given column 
def column_values(j, arr):
    temp=[]
    
    for i in range(9):
        temp.append(arr[i][j])
    
    temp1 = list(filter(lambda x: x!= 0, temp))
    
    temp2 = list(filter(lambda x: x not in temp1, digits))
    return temp2
print(column_values(0,arr))

[1, 5, 7, 8, 9]


In [339]:
modified_arr = copy.deepcopy(arr)


#Solving sudoko using row, colum, block non elements
def suduko_manipulation(arr, temp_arr):
    
    #Check for if any update is done or not
    flag = False
    
    #To keep the track of number of updates with given logic
    count = 0
    print('Array to update : ')
    print(temp_arr)
    
    
    for i in range(9):
        for j in range(9):
            
            #Value to update to slove sudoko
            if arr[i][j] ==0:
                print('Position to work on: ', i, j)
        
                row_items = row_values(i, temp_arr)
                column_items = column_values(j, temp_arr)
                block_items = block_values(i, j, temp_arr)
        
                print('row : {0} \ncolumnn: {1} \nblock : {2}'.format(row_items, column_items, block_items))
        
        
                updated_row =  list(filter(lambda x:  x in block_items, row_items))
                #print(updated_row)
        
                updated_column =  list(filter(lambda x:  x in block_items, column_items))
                #print(updated_column)
        
                common_items = list(filter(lambda x:  x in updated_row, updated_column))
                #print(common_items)
        
                key = str(i)+str(j)
                dict[key]= common_items
        
                
                #Possible options to update is one 
                if len(common_items) == 1:
                    print('Before updation : \n', temp_arr)
                    print('Updating..... Value to update: ',common_items[0] )
                    temp_arr[i][j]= common_items[0]
                    count +=1
                    print('After updation : \n', temp_arr)
                
                #More options to update
                else:
                    print('possible options are more.. NO UPDATION  \n')
                    
            
            #No need to update on given position as value is available
            else:
                print('No need to work on position ({},{}) value is {}'.format(i, j, temp_arr[i][j]))
            
            print()
            
    print('Total updates done in given iterations: ', count)
    if count>0:
        flag = True
        
    print('Updated value of flag is : ', flag)
    
    
    return (temp_arr, flag)

In [340]:
def Value_not_avalable(array):
    not_avaialble = list(filter(lambda x: x not in array, digits))
    if len(not_avaialble)==1:
        
        print('Value to be added : ', not_avaialble[0])
        return not_avaialble[0]
    
    elif len(not_avaialble) ==2:
        print('Values to be added : ', not_avaialble)
        return not_avaialble
Value_not_avalable([9, 2, 0, 0, 6, 7, 8, 4, 3])

Values to be added :  [1, 5]


[1, 5]

In [341]:
#Function for updating sudoko for single value for ROWS
def rowwise_update(arr):
    flag = False
    rows=  []
    
    #Created all rows in list
    for i in range(9):
        temp = []
        for j in range(9):
            temp.append(arr[i][j])
        #print(temp, i)
        rows.append(temp)
    
    
    #Finding total zereos and updating rows with single zero
    for row in rows:
    
        count =0
        for value in row:
        
            if value == 0:
                count+=1
        print('Zeros in {} : {} '.format(row, count))
    
        if count == 1:
            flag = True
            VALUE_TO_ADD = Value_not_avalable(row)
            print('Value to be added : ', VALUE_TO_ADD)
            
            for value in row:
                if value == 0:
                    print(row.index(value))
                    row[row.index(value)]= VALUE_TO_ADD
                    break
    return (np.array(rows), flag)
                
rowwise_arr, row_flag = rowwise_update(modified_array)

Zeros in [1, 5, 4, 8, 3, 7, 2, 6, 9] : 0 
Zeros in [6, 7, 2, 9, 5, 1, 8, 3, 4] : 0 
Zeros in [3, 8, 9, 2, 6, 4, 7, 5, 1] : 0 
Zeros in [9, 3, 8, 7, 2, 6, 4, 1, 5] : 0 
Zeros in [2, 1, 5, 3, 4, 8, 9, 7, 6] : 0 
Zeros in [7, 4, 6, 1, 9, 5, 3, 8, 2] : 0 
Zeros in [4, 2, 1, 5, 7, 3, 6, 9, 8] : 0 
Zeros in [8, 9, 7, 6, 1, 2, 5, 4, 3] : 0 
Zeros in [5, 6, 3, 4, 8, 9, 1, 2, 7] : 0 


In [342]:
#Function for updating sudoko for single value for Columns
def columnwise_update(arr):
    columns, column_flag = rowwise_update(np.transpose(arr))
    columns =  np.transpose(np.array(columns))
    return (columns, column_flag)

columnwise_arr, column_flag = columnwise_update(modified_array)

Zeros in [1, 6, 3, 9, 2, 7, 4, 8, 5] : 0 
Zeros in [5, 7, 8, 3, 1, 4, 2, 9, 6] : 0 
Zeros in [4, 2, 9, 8, 5, 6, 1, 7, 3] : 0 
Zeros in [8, 9, 2, 7, 3, 1, 5, 6, 4] : 0 
Zeros in [3, 5, 6, 2, 4, 9, 7, 1, 8] : 0 
Zeros in [7, 1, 4, 6, 8, 5, 3, 2, 9] : 0 
Zeros in [2, 8, 7, 4, 9, 3, 6, 5, 1] : 0 
Zeros in [6, 3, 5, 1, 7, 8, 9, 4, 2] : 0 
Zeros in [9, 4, 1, 5, 6, 2, 8, 3, 7] : 0 


In [343]:
def rowwise_update_2(array):
    flag = False
    rows=  []
    row_index = 0
    #Created all rows in list
    for i in range(9):
        temp = []
        for j in range(9):
            temp.append(array[i][j])

        rows.append(temp)
    
    
    #Finding total zereos and updating row with two zeros
    for row in rows:
        
        print('Current row index : ',row_index)
    
        count =0
        indices = []
        for i in range(len(row)):
            if row[i] == 0:
                indices.append(i)
                count+=1
        
    
        if count == 2:
            flag = True
            print('Total zeros in {} row : {} '.format(row, count))
            VALUE_TO_ADD = Value_not_avalable(row)
            print('Indices to work on : ', indices)
            
            
            for val in [VALUE_TO_ADD[0]]:
                
                print('VALUE TO WORK NOW : ',val )
                #Checking value is perfect for given position
                
                column = []
                for i in range(9):
                    column.append(array[i][indices[VALUE_TO_ADD.index(val)]])
                    
                print('Column elements: ', column )
                
                column_index = indices[VALUE_TO_ADD.index(val)]
                print('Position is : ',row_index, column_index)
                block = block_creation(row_index, column_index, array )
                print('Block elements :', block)
                print('Row elements: ', array[row_index])
                
                
                #1:Row wise validation
                if val not in row:
                    print('Satisfied row condition')
                    
                    #2:Column wise validation
                    if val not in column:
                        print('Satisfied column condition')

                        #3:Blockwise validation
                        
                        if val not in block:
                            print('Satisfied block condition')
                            
                            
                            print('Satisfied all 3 conditions .. checking for other element')
                            #Set the value for given position
                            #print('Before: ', array[row_index][column_index])
                            
                            
                            
                            #Checking other element
                            val = VALUE_TO_ADD[1]
                            
                            print('VALUE TO WORK NOW : ',val )
                            #Checking value is perfect for given position
                            column = []
                            for i in range(9):
                                column.append(array[i][indices[0]])
                    
                            print('Column elements: ', column )
                
                            column_index = indices[0]
                            print('Position is : ',row_index, column_index)
                            block = block_creation(row_index, column_index, array )
                            print('Block elements :', block)
                            print('Row elements: ', array[row_index])
                
                            
                
                
                            #1:Row wise validation
                            if val not in row:
                                print('Satisfied row condition')
                    
                                #2:Column wise validation
                                if val not in column:
                                    print('Satisfied column condition')

                                    #3:Blockwise validation
                        
                                    if val not in block:
                                        print('Satisfied block condition')
                                        #Set the value for given position
                                        print('Before: ', array[row_index][column_index])
                            
                                        print('PRESENT VAL IS: ', val)
                                        #array[row_index][column_index] =  val
                                        #print('After : ', array[row_index][column_index])
                                        
                                        
                                        #Checking for other location
                                        
                                        column_index = indices[1]
                                        print('Position is : ',row_index, column_index)
                                        print('Row elements: ', array[row_index])
                                        column = []
                                        for i in range(9):
                                            column.append(array[i][indices[1]])
                                        print('Column elements: ', column )
                                        
                            
                            
                                        if val not in row:
                                            print('Satisfied row condition')
                    
                                            #2:Column wise validation
                                            if val not in column:
                                                print('Satisfied column condition')
                         
                                                print('PRESENT VAL IS: ', val)
                                                continue
                                                print('Before : ', array[row_index][column_index])
                                                array[row_index][column_index] =  val
                                                array[row_index][indices[0]] =  VALUE_TO_ADD[0]
                                                print('After : ', array[row_index][column_index], array[row_index][indices[0]])
                                            else:
                                                print('Failing row condition')
                                                print('Before : ', array[row_index][column_index])
                                                array[row_index][column_index] = VALUE_TO_ADD[0] 
                                                array[row_index][indices[0]] =  val
                                                print('After : ', array[row_index][column_index], array[row_index][indices[0]])
                                                
                                        else:
                                            print('Failing row condition')
                                            print('Before : ', array[row_index][column_index])
                                            array[row_index][column_index] = VALUE_TO_ADD[0] 
                                            array[row_index][indices[0]] =  val
                                            print('After : ', array[row_index][column_index], array[row_index][indices[0]])   
                                        
                                        
                                    else:
                                        print('Failing block condition')
                                        #Set first value to given index
                                        print('Before: ', array[row_index][column_index])
                                        array[row_index][column_index] =  VALUE_TO_ADD[0]
                                        print('After : ', array[row_index][column_index]) 
                                else:
                                    print('Failing column condition')
                                    #Set first value to given index
                                    print('Before: ', array[row_index][column_index])
                                    array[row_index][column_index] =  VALUE_TO_ADD[0]
                                    print('After : ', array[row_index][column_index]) 
                                    
                            else:
                                print('Failing row condition')
                                #Set first value to given index
                                print('Before: ', array[row_index][column_index])
                                array[row_index][column_index] =  VALUE_TO_ADD[0]
                                print('After : ', array[row_index][column_index]) 
                                
                                        
                        else:
                            print('Failing block condition')
                            
                            
                            #Set another value to given index
                            print('Before: ', array[row_index][column_index])
                            array[row_index][column_index] =  VALUE_TO_ADD.remove(val)[0]
                            print('After : ', array[row_index][column_index])    
                            
                    else:
                        print('Failing column condition')
                        #Set another value to given index
                        print('Before: ', array[row_index][column_index])
                        array[row_index][column_index] =  VALUE_TO_ADD.remove(val)[0]
                        print('After : ', array[row_index][column_index])
                        
                    
                else:
                    print('Failing row condition')
                    
                    #Set another value to given index
                    print('Before: ', array[row_index][column_index])
                    array[row_index][column_index] =  VALUE_TO_ADD.remove(val)[0]
                    print('After : ', array[row_index][column_index])
                    
            print()
                    
        print(array)            
        row_index +=1
        
    return (array, flag)


In [359]:

if __name__ == "__main__":
    
    
    print('BLOCK 1'.center(40, '*'))
    array = copy.deepcopy(output_arr)
    modified_array =  copy.deepcopy(array)

    while zeros(array):
        print(zeros(array))
        modified_array, flag = suduko_manipulation(array, modified_array)

    
        array = copy.deepcopy(modified_array)
        print('\n\n')
    
        if flag==False:
            break
    
        
        
    print('Updated array for sudoko is : {} with number of zeros: {}'.format(modified_array, zeros(modified_array)))
    
    
    print('BLOCK 2'.center(40, '*'))
    #Checking for rowwise updates...
    print('Checking rowwise update for single element...')
    rowwise_arr, row_flag = rowwise_update(modified_array)
    if row_flag== True:
        print('Array updated ...\nNow checking for sudoko manipulation')
        array = copy.deepcopy(rowwise_arr)
        modified_array =  copy.deepcopy(rowwise_arr)

        while zeros(array):
            print(zeros(array))
            modified_array, flag = suduko_manipulation(array, modified_array)

    
            array = copy.deepcopy(modified_array)
    
            if flag==False:
                break
    else:
        print('No ROWWISE UPdate !!')
        
        
    print('After ROWWISE UPDATION Updated array for sudoko is : {} with number of zeros: {}'.format(modified_array, zeros(modified_array)))
    
    
    print('BLOCK 3'.center(40, '*'))
    #Checking for Columnwise updates...
    print('Checking columnwise update for single element...')
    
    columnwise_arr, column_flag = columnwise_update(modified_array)
    if column_flag == True:
        print('Array updated ...\nNow checking for sudoko manipulation')
        array = copy.deepcopy(columnwise_arr)
        modified_array =  copy.deepcopy(columnwise_arr)

        while zeros(array):
            print(zeros(array))
            modified_array, flag = suduko_manipulation(array, modified_array)

    
            array = copy.deepcopy(modified_array)
    
            if flag==False:
                break
    else:
        print('No COLUMN WISE update!!')
        
        
    print('After COLUMNWISE UPDATION Updated array for sudoko is : \n{} with number of zeros: {}'.format(modified_array, zeros(modified_array)))
    
    
    print('BLOCK 4'.center(40, '*'))
    #Checking for ROWWISE UPDATEE2
    print('Checking rowwise update for two elements...')
    arr_row_update2, modified_row_flag =rowwise_update_2(modified_array)
    
    if modified_row_flag == True:
        print('Array updated ...\nNow checking for sudoko manipulation')
        array = copy.deepcopy(arr_row_update2)
        modified_array =  copy.deepcopy(arr_row_update2)

        while zeros(array):
            print(zeros(array))
            modified_array, flag = suduko_manipulation(array, modified_array)

    
            array = copy.deepcopy(modified_array)
    
            if flag==False:
                break
    else:
        print('No ROWWISE UPDATEE2 update!!')
        
    
    
    print('BLOCK 5'.center(40, '*'))
    modified_array_T = np.transpose(modified_array)
    
    #Checking for ROWWISE UPDATEE2
    print('Checking COLUMN WISE update for two elements...')
    arr_col_update2, modified_col_flag =rowwise_update_2(modified_array_T)
    
    if modified_col_flag == True:
        print('Array updated ...\nNow checking for sudoko manipulation')
        array = copy.deepcopy(arr_col_update2)
        modified_array =  copy.deepcopy(arr_col_update2)

        while zeros(array):
            print(zeros(array))
            modified_array, flag = suduko_manipulation(array, modified_array)

    
            array = copy.deepcopy(modified_array)
    
            if flag==False:
                break
    else:
        print('No COLUMN WISE UPDATEE2 update!!')
    
    modified_array = np.transpose(modified_array)
    
    
    print('\n\n\n')
    print(modified_array)
    
    
    print('BLOCK 7'.center(40, '*'))
    #Checking for rowwise updates...
    print('Checking rowwise update for single element...')
    rowwise_arr, row_flag = rowwise_update(modified_array)
    if row_flag== True:
        print('Array updated ...\nNow checking for sudoko manipulation')
        array = copy.deepcopy(rowwise_arr)
        modified_array =  copy.deepcopy(rowwise_arr)

        while zeros(array):
            print(zeros(array))
            modified_array, flag = suduko_manipulation(array, modified_array)

    
            array = copy.deepcopy(modified_array)
    
            if flag==False:
                break
    else:
        print('No ROWWISE UPdate !!')
        
        
    print('After ROWWISE UPDATION Updated array for sudoko is : {} with number of zeros: {}'.format(modified_array, zeros(modified_array)))
    
    
    
    modified_array = np.transpose(modified_array)

    for i in modified_array:
        temp =0
        for j in i:
            temp +=j
        print(i, temp)
            

****************BLOCK 1*****************
45
Array to update : 
[[0 0 4 0 0 6 0 7 9]
 [0 0 0 0 0 0 6 0 2]
 [0 5 6 0 9 2 3 0 0]
 [0 7 8 0 6 1 0 3 0]
 [5 0 9 0 0 0 4 0 6]
 [0 2 0 5 4 0 8 9 0]
 [0 0 7 4 1 0 9 2 0]
 [1 0 5 0 0 0 0 0 0]
 [8 4 0 6 0 0 1 0 0]]
Position to work on:  0 0
row : [1, 2, 3, 5, 8] 
columnn: [2, 3, 4, 6, 7, 9] 
block : [1, 2, 3, 7, 8, 9]
possible options are more.. NO UPDATION  


Position to work on:  0 1
row : [1, 2, 3, 5, 8] 
columnn: [1, 3, 6, 8, 9] 
block : [1, 2, 3, 7, 8, 9]
possible options are more.. NO UPDATION  


No need to work on position (0,2) value is 4

Position to work on:  0 3
row : [1, 2, 3, 5, 8] 
columnn: [1, 2, 3, 7, 8, 9] 
block : [1, 3, 4, 5, 7, 8]
possible options are more.. NO UPDATION  


Position to work on:  0 4
row : [1, 2, 3, 5, 8] 
columnn: [2, 3, 5, 7, 8] 
block : [1, 3, 4, 5, 7, 8]
possible options are more.. NO UPDATION  


No need to work on position (0,5) value is 6

Position to work on:  0 6
row : [1, 2, 3, 5, 8] 
columnn: [2, 5, 